name: Transform text.txt into ublock.txt and leechblock.txt

on:
  push:
    branches:
      - main

jobs:
  duplicate_and_modify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Pull repo
        run: git pull origin main

      - name: Transform text.txt into ublock.txt
        run: |
          > ublock.txt
          while IFS= read -r line; do
            if [ -n "$line" ]; then
              echo "||${line}^" >> ublock.txt
            else
              echo "" >> ublock.txt
            fi
          done < text.txt

      - name: Transform text.txt into leechblock.txt
        run: |
          > leechblock.txt
          while IFS= read -r line; do
            if [ -n "$line" ]; then
              echo "${line}*" >> leechblock.txt
            else
              echo "" >> leechblock.txt
            fi
          done < text.txt

      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@users.noreply.github.com"
          git add .
          git commit -m "Transformed them files"
          git push
