name: Generate Pre-Signed URL

on: [push, workflow_dispatch]

jobs:
  generate-url:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository content
      uses: actions/checkout@v2

    - name: Generate Pre-Signed URL
      id: generate_url
      run: |
        FILE_PATH="blocklists/leechblock.txt"
        URL="https://github.com/${{ github.repository }}/raw/${{ github.ref_name }}/${FILE_PATH}"
        echo "::set-output name=url::${URL}"

    - name: Print Pre-Signed URL
      run: echo "Pre-Signed URL: ${{ steps.generate_url.outputs.url }}"
